- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .gitmodules
- Makefile
- build.sh
- config/ci.json
- config/dev.json
- config/prod.json
- contracts/DebtLocker.sol
- contracts/interfaces/IDebtLocker.sol
- contracts/interfaces/IDebtLockerFactory.sol
- contracts/interfaces/ILoan.sol
- contracts/test/DebtLockerFactory.t.sol
- contracts/test/accounts/DebtLockerOwner.sol
- test.sh
> chore: Fix modules, tests, and CI (SC-3053)

- contracts/DebtLocker.sol
- contracts/interfaces/IDebtLocker.sol
- contracts/interfaces/ILoanLike.sol
- contracts/test/DebtLockerFactory.t.sol
> chore: Mock fixes

- .gitignore
- Makefile
- release.sh
> feat: Make Release

- Makefile
- package.yaml
- release.sh
> feat: Better Make Release

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .gitmodules
- Makefile
- build.sh
- config/ci.json
- config/dev.json
- config/prod.json
- contracts/DebtLocker.sol
- contracts/interfaces/IDebtLocker.sol
- contracts/interfaces/IDebtLockerFactory.sol
- contracts/interfaces/ILoan.sol
- contracts/interfaces/ILoanLike.sol
- contracts/test/DebtLockerFactory.t.sol
- contracts/test/accounts/DebtLockerOwner.sol
- package.yaml
- release.sh
- test.sh
> chore: Update `main` branch for consumption

- contracts/DebtLocker.sol
- contracts/DebtLockerStorage.sol
- contracts/interfaces/IDebtLocker.sol
- contracts/test/DebtLocker.t.sol
- contracts/test/accounts/PoolDelegate.sol
> feat: Capture Funds

- README.md
- contracts/DebtLocker.sol
- contracts/test/DebtLocker.t.sol
This branch will be used to capture changes over the course of the internal audit
> chore: Make internal audit changes

- .gitmodules
> fix: Remove unused subfactory submodule

- contracts/test/DebtLocker.t.sol
> fix: Test shortfall ocasionally failing

- contracts/DebtLockerFactory.sol
> chore: chore: Prevent zero `mapleGlobals` in factory deployment

- contracts/DebtLocker.sol
- contracts/interfaces/IDebtLocker.sol
- contracts/test/DebtLocker.t.sol
- contracts/test/accounts/PoolDelegate.sol
> feat: Manual `stopLiquidation` function to prevent `claim` DoS (SC-4211)

- contracts/DebtLocker.sol
- contracts/DebtLockerStorage.sol
- contracts/test/DebtLocker.t.sol
> chore: CEI (event emissions before interactions, where possible) (SC-4151)

- config/ci.json
- config/dev.json
- config/prod.json
- contracts/DebtLocker.sol
- contracts/DebtLockerFactory.sol
- contracts/DebtLockerStorage.sol
- contracts/interfaces/IDebtLockerFactory.sol
- contracts/test/DebtLocker.t.sol
- package.yaml
> feat: Cleanup and Proxy Determinism

- contracts/DebtLocker.sol
- contracts/DebtLockerFactory.sol
- contracts/test/DebtLocker.t.sol
- contracts/test/accounts/PoolDelegate.sol
- contracts/test/mocks/DebtLockerHarness.sol
- contracts/test/mocks/ManipulatableDebtLocker.sol
- contracts/test/mocks/Mocks.sol
> feat: Cleanup and more unit testing

- contracts/DebtLocker.sol
- contracts/interfaces/IDebtLocker.sol
- contracts/interfaces/Interfaces.sol
- contracts/test/DebtLocker.t.sol
- contracts/test/mocks/Mocks.sol
> feat: Add global pause (SC-4215)

- contracts/DebtLocker.sol
Addresses https://github.com/code-423n4/2021-12-maple-findings/issues/10
> chore: Remove TODO on pullFunds (C4 #10)

- contracts/DebtLocker.sol
- contracts/test/DebtLocker.t.sol
> fix: Input validation for `setAllowedSlippage` (c4 #45)

- contracts/DebtLocker.sol
- contracts/interfaces/IDebtLocker.sol
- contracts/test/DebtLocker.t.sol
- contracts/test/accounts/PoolDelegate.sol
> feat: Add liquidator address to pullFunds parameters (SC-4344)

- README.md
> Feat:  Readme update (SC-4527)

- README.md
> feat: Update README audit links
